### ISSUE TITLE
Scam “repo” 

### ISSUE THREAD

**Issue by iDevOps-pl** [iOS17/Jailbreak#12]
Why you post useless info ? Marked as bullshit

**Comment by iOS17** [comment]
Sorry to hear about that, and I'd like to ask you what the scam is here. Please explain. Also, the best method for reporting an issue is to thoroughly study the facts and instructions before opening the issue.  Also, if you think the data is a fraud, do not read it. However, we have covered all legitimate data found in the jailbreak community. These data are not always useful for ultra legends, but we have opened this repository to basic users.
