### ISSUE TITLE
Too fake

### ISSUE THREAD

**Issue by RisingGlitch** [iOS17/Jailbreak#15]
At least make it convincing smh,

**Comment by iOS17** [comment]
Please explain what the fake parts are, and make sure to comment on at least one fake thing in this repo the next time you comment. So we can fix it with your contribution.

**Comment by RisingGlitch** [comment]
Everything,

**Comment by iOS17** [comment]
Yes, we now have an idea of your capacity 👎 . Anyway, thank you for commenting.
![image](https://github.com/iOS17/Jailbreak/assets/135683347/39097a87-a652-4d39-9753-683ec3036f6a)
