### ISSUE TITLE
How trust worthy is this? Data loss?

### ISSUE THREAD

**Issue by v4an1shed** [iOS17/Jailbreak#2]
How new is this and why would you recommend using these iOS17 jailbreak methods? 
[The creator didn’t answer, this is a scam btw]

**Comment by SirMishaa** [comment]
> How new is this and why would you recommend using these iOS17 jailbreak methods? [The creator didn’t answer, this is a scam btw]

Indeed, this is a big scam. 
If you want true documentation, it's here : https://ios.cfw.guide/get-started/select-iphone/
