### ISSUE TITLE
iOS 17.0.1 iPhone 13 Pro 

### ISSUE THREAD

**Issue by kfady1001** [iOS17/Jailbreak#5]
<Warning>: Ignoring non-arm64 device..

that's the result always I get while Sam trying to jailbreak iPhone 13 Pro iOS 17.0.1

**Comment by kfady1001** [comment]
![Uploading Screenshot 2023-11-16 at 2.16.00 AM.png…]()

**Comment by EpicGamer243** [comment]
No shit, Palera1n is ONLY for arm64 (iPhone X and lower.) your phone is NOT COMPATIBLE

**Comment by brurmonemt** [comment]
its called an unsupported device s0n
